import Column from '@/interface/Column';
import CompleteTableRow from '@/interface/CompletTableRow'; 
import { TableRow } from '@/interface/RowPayments';

export default class Data {
    // Atualizando a função createData para usar CompleteTableRow
    static createData(
        nomeCompleto: string,
        registroFuncional: string,
        cpf: string,
        nomeSocial: string,
        sexo: string,
        racaCor: string,
        grupoSanguineo: string,
        dataNascimento: Date,
        pais: string,
        possuidorDeficiencia: boolean,
        tipoDeficiencia: string,
        uf: string,
        cidade: string,
        estadoCivil: string,
        escolaridade: string,
        nacionalidade: string,
        numIdentidadeProfissional: string,
        conselhoIdentidadeProfissional: string,
        profissaoIdentidadeProfissional: string,
        dataExpedicaoIdentidadeProfissional: Date,
        especificacaoFormacao: string,
        anoChegadaBrasil: number,
        anoPrimeiroEmprego: number,
        existenciaCadastroCertidoes: string,
        endereco: string,
        cargoFuncao: string,
        referenciaCargoFuncao: string,
        provimentoCargoFuncao: string,
        dataInicioCargoFuncao: Date,
        dataExoneracaoCargoFuncao: Date,
        codigoUnidadeSIMPROC: string,
        codigoUnidadeSEI: string,
        cargoComissao: string,
        referenciaCargoComissao: string,
        dataInicioCargoComissao: Date,
        dataTerminoCargoComissao: Date,
        unidadeLotacaoCargoComissao: string,
        departamentoCoordenadoriaCargoComissao: string,
        provimentoCargas: string,
        cargosLivresOcupados: string,
        impedimentosLegais: string,
        dataInicioImpedimentosLegais: Date,
        dataTerminoImpedimentosLegais: Date
    ): CompleteTableRow {
        return {
            nomeCompleto,
            registroFuncional,
            cpf,
            nomeSocial,
            sexo,
            racaCor,
            grupoSanguineo,
            dataNascimento,
            pais,
            possuidorDeficiencia,
            tipoDeficiencia,
            uf,
            cidade,
            estadoCivil,
            escolaridade,
            nacionalidade,
            numIdentidadeProfissional,
            conselhoIdentidadeProfissional,
            profissaoIdentidadeProfissional,
            dataExpedicaoIdentidadeProfissional,
            especificacaoFormacao,
            anoChegadaBrasil,
            anoPrimeiroEmprego,
            existenciaCadastroCertidoes,
            endereco,
            cargoFuncao,
            referenciaCargoFuncao,
            provimentoCargoFuncao,
            dataInicioCargoFuncao,
            dataExoneracaoCargoFuncao,
            codigoUnidadeSIMPROC,
            codigoUnidadeSEI,
            cargoComissao,
            referenciaCargoComissao,
            dataInicioCargoComissao,
            dataTerminoCargoComissao,
            unidadeLotacaoCargoComissao,
            departamentoCoordenadoriaCargoComissao,
            provimentoCargas,
            cargosLivresOcupados,
            impedimentosLegais,
            dataInicioImpedimentosLegais,
            dataTerminoImpedimentosLegais
        };
    }

    
    static get_columns_test():Column[] {
        return [
            { header: 'Nome Social', accessor: 'nomeSocial', type: 'text'},
            { header: 'Registro Funcional', accessor: 'registroFuncional', type: 'text'},
            { header: 'Nome', accessor: 'nomeCompleto', type: 'text'},
            { header: 'Registro Funcional 2', accessor: 'registroFuncional', type: 'text'},
            { header: 'Substituto (sem dados)', accessor: 'uf', type: 'text'},
            { header: 'Cargo', accessor: 'cargoComissao', type: 'text'},
            { header: 'Referência', accessor: 'referenciaCargoComissao', type: 'text'},
            { header: 'Mês de Referência', accessor: 'dataExoneracaoCargoFuncao', type: 'date'},
            { header: 'Início', accessor: 'dataInicioCargoComissao', type: 'date'},
            { header: 'Fim', accessor: 'dataTerminoCargoComissao', type: 'date'},
            { header: 'Motivo (sem dados)', accessor: 'uf', type: 'text'},
            { header: 'Documento (sem dados)', accessor: 'uf', type: 'text'},
            { header: 'Conferência (sem dados)', accessor: 'uf', type: 'text'},
            { header: 'Observação (sem dados)', accessor: 'uf', type: 'text' }
        ];
    };

    // Atualizando filter_rows para usar CompleteTableRow
    static filter_rows = (rows: CompleteTableRow[], column: string, value: string, dateRange?: [Date | null, Date | null]): CompleteTableRow[] => {
        if (dateRange) {
            return this.filterRowsByDate(rows, column, dateRange);
        } else {
            // Filtro de texto
            return rows.filter(row => {
                const cellValue = (row as any)[column];
                return cellValue && cellValue.toString().includes(value);
            });
        }
    };
    
    static filterRowsByDate = (rows: CompleteTableRow[], column: string, dateRange: [Date | null, Date | null]): CompleteTableRow[] => {
        const [startDate, endDate] = dateRange;
        
        return rows.filter(row => {
            const cellValue = new Date((row as any)[column]);
            return (!startDate || cellValue >= startDate) && (!endDate || cellValue <= endDate);
        });
    };
    
    // Atualizando format_filter_rows para usar CompleteTableRow
    static format_filter_rows(rows: CompleteTableRow[]): CompleteTableRow[] {
        return rows.map(row => ({
            ...row,
            pago: row.possuidorDeficiencia ? true : false,  // Exemplo de conversão para o campo 'pago'
            valor: 0,  // Ajuste conforme necessário
        }));
    }    
    
    static formatDate(dateString: string): string {
        const date = new Date(dateString);
        const day = String(date.getDate()).padStart(2, '0');
        const month = String(date.getMonth() + 1).padStart(2, '0');
        const year = date.getFullYear();
        return `${day}/${month}/${year}`;
    }
    
    static get_data_test(): CompleteTableRow[] {
        const rows: CompleteTableRow[] = [
            {
                nomeCompleto: 'Lucas Santos',
                registroFuncional: 'RF123',
                cpf: '123.456.789-00',
                nomeSocial: 'Lucas',
                sexo: 'Masculino',
                racaCor: 'Pardo',
                grupoSanguineo: 'O+',
                dataNascimento: new Date('1980-01-01'),
                pais: 'Brasil',
                possuidorDeficiencia: true,
                tipoDeficiencia: 'Nenhuma',
                uf: 'SP',
                cidade: 'São Paulo',
                estadoCivil: 'Casado',
                escolaridade: 'Superior Completo',
                nacionalidade: 'Brasileiro',
                numIdentidadeProfissional: '1234567',
                conselhoIdentidadeProfissional: 'CREA-SP',
                profissaoIdentidadeProfissional: 'Engenheiro',
                dataExpedicaoIdentidadeProfissional: new Date('2000-01-01'),
                especificacaoFormacao: 'Engenharia',
                anoChegadaBrasil: 2000,
                anoPrimeiroEmprego: 2010,
                existenciaCadastroCertidoes: 'Sim',
                endereco: 'Rua Exemplo, 123',
                cargoFuncao: 'Engenheiro',
                referenciaCargoFuncao: 'A1',
                provimentoCargoFuncao: 'Efetivo',
                dataInicioCargoFuncao: new Date('2000-01-01'),
                dataExoneracaoCargoFuncao: new Date('2010-01-01'),
                codigoUnidadeSIMPROC: 'S123',
                codigoUnidadeSEI: 'E123',
                cargoComissao: 'Comissionado',
                referenciaCargoComissao: 'A1',
                dataInicioCargoComissao: new Date('2001-01-01'),
                dataTerminoCargoComissao: new Date('2010-01-01'),
                unidadeLotacaoCargoComissao: 'Unidade 1',
                departamentoCoordenadoriaCargoComissao: 'Departamento 1',
                provimentoCargas: 'Posse',
                cargosLivresOcupados: '2',
                impedimentosLegais: 'Nenhum',
                dataInicioImpedimentosLegais: new Date('2000-01-01'),
                dataTerminoImpedimentosLegais: new Date('2010-01-01')
            },
            {
                nomeCompleto: 'João Silva',
                registroFuncional: 'RF124',
                cpf: '123.111.789-01',
                nomeSocial: 'João',
                sexo: 'Masculino',
                racaCor: 'Branco',
                grupoSanguineo: 'A+',
                dataNascimento: new Date('1985-02-15'),
                pais: 'Brasil',
                possuidorDeficiencia: false,
                tipoDeficiencia: 'Nenhuma',
                uf: 'RJ',
                cidade: 'Rio de Janeiro',
                estadoCivil: 'Solteiro',
                escolaridade: 'Médio Completo',
                nacionalidade: 'Brasileiro',
                numIdentidadeProfissional: '2345678',
                conselhoIdentidadeProfissional: 'CREA-RJ',
                profissaoIdentidadeProfissional: 'Analista',
                dataExpedicaoIdentidadeProfissional: new Date('2005-02-01'),
                especificacaoFormacao: 'Tecnologia',
                anoChegadaBrasil: 2005,
                anoPrimeiroEmprego: 2015,
                existenciaCadastroCertidoes: 'Não',
                endereco: 'Av. Exemplo, 456',
                cargoFuncao: 'Analista',
                referenciaCargoFuncao: 'B2',
                provimentoCargoFuncao: 'Temporário',
                dataInicioCargoFuncao: new Date('2010-05-01'),
                dataExoneracaoCargoFuncao: new Date('2015-05-01'),
                codigoUnidadeSIMPROC: 'S124',
                codigoUnidadeSEI: 'E124',
                cargoComissao: 'Comissionado',
                referenciaCargoComissao: 'B2',
                dataInicioCargoComissao: new Date('2011-05-01'),
                dataTerminoCargoComissao: new Date('2015-05-01'),
                unidadeLotacaoCargoComissao: 'Unidade 2',
                departamentoCoordenadoriaCargoComissao: 'Departamento 2',
                provimentoCargas: 'Posse',
                cargosLivresOcupados: '1',
                impedimentosLegais: 'Nenhum',
                dataInicioImpedimentosLegais: new Date('2005-05-01'),
                dataTerminoImpedimentosLegais: new Date('2015-05-01')
            },
            {
                nomeCompleto: 'Maria Oliveira',
                registroFuncional: 'RF125',
                cpf: '123.222.789-02',
                nomeSocial: 'Maria',
                sexo: 'Feminino',
                racaCor: 'Negra',
                grupoSanguineo: 'O-',
                dataNascimento: new Date('1990-03-10'),
                pais: 'Brasil',
                possuidorDeficiencia: true,
                tipoDeficiencia: 'Visual',
                uf: 'MG',
                cidade: 'Belo Horizonte',
                estadoCivil: 'Divorciada',
                escolaridade: 'Superior Completo',
                nacionalidade: 'Brasileira',
                numIdentidadeProfissional: '3456789',
                conselhoIdentidadeProfissional: 'CRN-MG',
                profissaoIdentidadeProfissional: 'Nutricionista',
                dataExpedicaoIdentidadeProfissional: new Date('2010-03-15'),
                especificacaoFormacao: 'Nutrição',
                anoChegadaBrasil: 2010,
                anoPrimeiroEmprego: 2020,
                existenciaCadastroCertidoes: 'Sim',
                endereco: 'Rua Exemplo, 789',
                cargoFuncao: 'Nutricionista',
                referenciaCargoFuncao: 'C3',
                provimentoCargoFuncao: 'Efetivo',
                dataInicioCargoFuncao: new Date('2015-03-01'),
                dataExoneracaoCargoFuncao: new Date('2020-03-01'),
                codigoUnidadeSIMPROC: 'S125',
                codigoUnidadeSEI: 'E125',
                cargoComissao: 'Comissionado',
                referenciaCargoComissao: 'C3',
                dataInicioCargoComissao: new Date('2016-03-01'),
                dataTerminoCargoComissao: new Date('2020-03-01'),
                unidadeLotacaoCargoComissao: 'Unidade 3',
                departamentoCoordenadoriaCargoComissao: 'Departamento 3',
                provimentoCargas: 'Posse',
                cargosLivresOcupados: '0',
                impedimentosLegais: 'Nenhum',
                dataInicioImpedimentosLegais: new Date('2010-03-01'),
                dataTerminoImpedimentosLegais: new Date('2020-03-01')
            },
            {
                nomeCompleto: 'Pedro Costa',
                registroFuncional: 'RF126',
                cpf: '123.333.789-03',
                nomeSocial: 'Pedro',
                sexo: 'Masculino',
                racaCor: 'Pardo',
                grupoSanguineo: 'B+',
                dataNascimento: new Date('1992-04-20'),
                pais: 'Brasil',
                possuidorDeficiencia: false,
                tipoDeficiencia: 'Nenhuma',
                uf: 'BA',
                cidade: 'Salvador',
                estadoCivil: 'Casado',
                escolaridade: 'Técnico',
                nacionalidade: 'Brasileiro',
                numIdentidadeProfissional: '4567890',
                conselhoIdentidadeProfissional: 'CREA-BA',
                profissaoIdentidadeProfissional: 'Técnico',
                dataExpedicaoIdentidadeProfissional: new Date('2015-04-10'),
                especificacaoFormacao: 'Técnico',
                anoChegadaBrasil: 2015,
                anoPrimeiroEmprego: 2025,
                existenciaCadastroCertidoes: 'Não',
                endereco: 'Rua Central, 101',
                cargoFuncao: 'Técnico',
                referenciaCargoFuncao: 'D4',
                provimentoCargoFuncao: 'Temporário',
                dataInicioCargoFuncao: new Date('2020-04-01'),
                dataExoneracaoCargoFuncao: new Date('2025-04-01'),
                codigoUnidadeSIMPROC: 'S126',
                codigoUnidadeSEI: 'E126',
                cargoComissao: 'Comissionado',
                referenciaCargoComissao: 'D4',
                dataInicioCargoComissao: new Date('2021-04-01'),
                dataTerminoCargoComissao: new Date('2025-04-01'),
                unidadeLotacaoCargoComissao: 'Unidade 4',
                departamentoCoordenadoriaCargoComissao: 'Departamento 4',
                provimentoCargas: 'Posse',
                cargosLivresOcupados: '1',
                impedimentosLegais: 'Nenhum',
                dataInicioImpedimentosLegais: new Date('2015-04-01'),
                dataTerminoImpedimentosLegais: new Date('2025-04-01')
            },
            {
                nomeCompleto: 'Ana Souza',
                registroFuncional: 'RF127',
                cpf: '123.444.789-04',
                nomeSocial: 'Ana',
                sexo: 'Feminino',
                racaCor: 'Branca',
                grupoSanguineo: 'A-',
                dataNascimento: new Date('1978-12-05'),
                pais: 'Brasil',
                possuidorDeficiencia: false,
                tipoDeficiencia: 'Nenhuma',
                uf: 'RS',
                cidade: 'Porto Alegre',
                estadoCivil: 'Solteira',
                escolaridade: 'Superior Completo',
                nacionalidade: 'Brasileira',
                numIdentidadeProfissional: '5678901',
                conselhoIdentidadeProfissional: 'CRN-RS',
                profissaoIdentidadeProfissional: 'Psicóloga',
                dataExpedicaoIdentidadeProfissional: new Date('2010-01-01'),
                especificacaoFormacao: 'Psicologia',
                anoChegadaBrasil: 2010,
                anoPrimeiroEmprego: 2020,
                existenciaCadastroCertidoes: 'Sim',
                endereco: 'Rua Principal, 200',
                cargoFuncao: 'Psicóloga',
                referenciaCargoFuncao: 'E5',
                provimentoCargoFuncao: 'Efetivo',
                dataInicioCargoFuncao: new Date('2015-01-01'),
                dataExoneracaoCargoFuncao: new Date('2020-01-01'),
                codigoUnidadeSIMPROC: 'S127',
                codigoUnidadeSEI: 'E127',
                cargoComissao: 'Comissionado',
                referenciaCargoComissao: 'E5',
                dataInicioCargoComissao: new Date('2016-01-01'),
                dataTerminoCargoComissao: new Date('2020-01-01'),
                unidadeLotacaoCargoComissao: 'Unidade 5',
                departamentoCoordenadoriaCargoComissao: 'Departamento 5',
                provimentoCargas: 'Posse',
                cargosLivresOcupados: '2',
                impedimentosLegais: 'Nenhum',
                dataInicioImpedimentosLegais: new Date('2010-01-01'),
                dataTerminoImpedimentosLegais: new Date('2020-01-01')
            },
            {
                nomeCompleto: 'Carlos Almeida',
                registroFuncional: 'RF128',
                cpf: '123.555.789-05',
                nomeSocial: 'Carlos',
                sexo: 'Masculino',
                racaCor: 'Pardo',
                grupoSanguineo: 'O+',
                dataNascimento: new Date('1982-11-20'),
                pais: 'Brasil',
                possuidorDeficiencia: true,
                tipoDeficiencia: 'Auditivo',
                uf: 'SP',
                cidade: 'São Paulo',
                estadoCivil: 'Casado',
                escolaridade: 'Superior Completo',
                nacionalidade: 'Brasileiro',
                numIdentidadeProfissional: '6789012',
                conselhoIdentidadeProfissional: 'CREA-SP',
                profissaoIdentidadeProfissional: 'Engenheiro',
                dataExpedicaoIdentidadeProfissional: new Date('2005-01-01'),
                especificacaoFormacao: 'Engenharia',
                anoChegadaBrasil: 2005,
                anoPrimeiroEmprego: 2015,
                existenciaCadastroCertidoes: 'Sim',
                endereco: 'Av. Central, 500',
                cargoFuncao: 'Engenheiro',
                referenciaCargoFuncao: 'F6',
                provimentoCargoFuncao: 'Efetivo',
                dataInicioCargoFuncao: new Date('2010-01-01'),
                dataExoneracaoCargoFuncao: new Date('2015-01-01'),
                codigoUnidadeSIMPROC: 'S128',
                codigoUnidadeSEI: 'E128',
                cargoComissao: 'Comissionado',
                referenciaCargoComissao: 'F6',
                dataInicioCargoComissao: new Date('2011-01-01'),
                dataTerminoCargoComissao: new Date('2015-01-01'),
                unidadeLotacaoCargoComissao: 'Unidade 6',
                departamentoCoordenadoriaCargoComissao: 'Departamento 6',
                provimentoCargas: 'Posse',
                cargosLivresOcupados: '1',
                impedimentosLegais: 'Nenhum',
                dataInicioImpedimentosLegais: new Date('2005-01-01'),
                dataTerminoImpedimentosLegais: new Date('2015-01-01')
            },
            {
                nomeCompleto: 'Juliana Mendes',
                registroFuncional: 'RF129',
                cpf: '123.666.789-06',
                nomeSocial: 'Juliana',
                sexo: 'Feminino',
                racaCor: 'Negra',
                grupoSanguineo: 'AB-',
                dataNascimento: new Date('1995-02-14'),
                pais: 'Brasil',
                possuidorDeficiencia: false,
                tipoDeficiencia: 'Nenhuma',
                uf: 'MG',
                cidade: 'Belo Horizonte',
                estadoCivil: 'Solteira',
                escolaridade: 'Superior Completo',
                nacionalidade: 'Brasileira',
                numIdentidadeProfissional: '7890123',
                conselhoIdentidadeProfissional: 'CRN-MG',
                profissaoIdentidadeProfissional: 'Assistente Social',
                dataExpedicaoIdentidadeProfissional: new Date('2015-02-15'),
                especificacaoFormacao: 'Serviço Social',
                anoChegadaBrasil: 2015,
                anoPrimeiroEmprego: 2025,
                existenciaCadastroCertidoes: 'Não',
                endereco: 'Rua Secundária, 600',
                cargoFuncao: 'Assistente Social',
                referenciaCargoFuncao: 'G7',
                provimentoCargoFuncao: 'Temporário',
                dataInicioCargoFuncao: new Date('2020-02-01'),
                dataExoneracaoCargoFuncao: new Date('2025-02-01'),
                codigoUnidadeSIMPROC: 'S129',
                codigoUnidadeSEI: 'E129',
                cargoComissao: 'Comissionado',
                referenciaCargoComissao: 'G7',
                dataInicioCargoComissao: new Date('2021-02-01'),
                dataTerminoCargoComissao: new Date('2025-02-01'),
                unidadeLotacaoCargoComissao: 'Unidade 7',
                departamentoCoordenadoriaCargoComissao: 'Departamento 7',
                provimentoCargas: 'Posse',
                cargosLivresOcupados: '0',
                impedimentosLegais: 'Nenhum',
                dataInicioImpedimentosLegais: new Date('2015-02-01'),
                dataTerminoImpedimentosLegais: new Date('2025-02-01')
            },
            {   
                nomeCompleto: 'Lucas Santos',
                registroFuncional: 'RF123',
                cpf: '123.456.789-00',
                nomeSocial: 'Lucas',
                sexo: 'Masculino',
                racaCor: 'Pardo',
                grupoSanguineo: 'O+',
                dataNascimento: new Date('1980-01-01'),
                pais: 'Brasil',
                possuidorDeficiencia: true,
                tipoDeficiencia: 'Nenhuma',
                uf: 'SP',
                cidade: 'São Paulo',
                estadoCivil: 'Casado',
                escolaridade: 'Superior Completo',
                nacionalidade: 'Brasileiro',
                numIdentidadeProfissional: '1234567',
                conselhoIdentidadeProfissional: 'CREA-SP',
                profissaoIdentidadeProfissional: 'Engenheiro',
                dataExpedicaoIdentidadeProfissional: new Date('2000-01-01'),
                especificacaoFormacao: 'Engenharia',
                anoChegadaBrasil: 2000,
                anoPrimeiroEmprego: 2010,
                existenciaCadastroCertidoes: 'Sim',
                endereco: 'Rua Exemplo, 123',
                cargoFuncao: 'Engenheiro',
                referenciaCargoFuncao: 'A1',
                provimentoCargoFuncao: 'Efetivo',
                dataInicioCargoFuncao: new Date('2000-01-01'),
                dataExoneracaoCargoFuncao: new Date('2010-01-01'),
                codigoUnidadeSIMPROC: 'S123',
                codigoUnidadeSEI: 'E123',
                cargoComissao: 'Comissionado',
                referenciaCargoComissao: 'A1',
                dataInicioCargoComissao: new Date('2001-01-01'),
                dataTerminoCargoComissao: new Date('2010-01-01'),
                unidadeLotacaoCargoComissao: 'Unidade 1',
                departamentoCoordenadoriaCargoComissao: 'Departamento 1',
                provimentoCargas: 'Posse',
                cargosLivresOcupados: '2',
                impedimentosLegais: 'Nenhum',
                dataInicioImpedimentosLegais: new Date('2000-01-01'),
                dataTerminoImpedimentosLegais: new Date('2010-01-01')
            },
            {
                nomeCompleto: 'João Silva',
                registroFuncional: 'RF124',
                cpf: '123.111.789-01',
                nomeSocial: 'João',
                sexo: 'Masculino',
                racaCor: 'Branco',
                grupoSanguineo: 'A+',
                dataNascimento: new Date('1985-02-15'),
                pais: 'Brasil',
                possuidorDeficiencia: false,
                tipoDeficiencia: 'Nenhuma',
                uf: 'RJ',
                cidade: 'Rio de Janeiro',
                estadoCivil: 'Solteiro',
                escolaridade: 'Médio Completo',
                nacionalidade: 'Brasileiro',
                numIdentidadeProfissional: '2345678',
                conselhoIdentidadeProfissional: 'CREA-RJ',
                profissaoIdentidadeProfissional: 'Analista',
                dataExpedicaoIdentidadeProfissional: new Date('2005-02-01'),
                especificacaoFormacao: 'Tecnologia',
                anoChegadaBrasil: 2005,
                anoPrimeiroEmprego: 2015,
                existenciaCadastroCertidoes: 'Não',
                endereco: 'Av. Exemplo, 456',
                cargoFuncao: 'Analista',
                referenciaCargoFuncao: 'B2',
                provimentoCargoFuncao: 'Temporário',
                dataInicioCargoFuncao: new Date('2010-05-01'),
                dataExoneracaoCargoFuncao: new Date('2015-05-01'),
                codigoUnidadeSIMPROC: 'S124',
                codigoUnidadeSEI: 'E124',
                cargoComissao: 'Comissionado',
                referenciaCargoComissao: 'B2',
                dataInicioCargoComissao: new Date('2011-05-01'),
                dataTerminoCargoComissao: new Date('2015-05-01'),
                unidadeLotacaoCargoComissao: 'Unidade 2',
                departamentoCoordenadoriaCargoComissao: 'Departamento 2',
                provimentoCargas: 'Posse',
                cargosLivresOcupados: '1',
                impedimentosLegais: 'Nenhum',
                dataInicioImpedimentosLegais: new Date('2005-05-01'),
                dataTerminoImpedimentosLegais: new Date('2015-05-01')
            },
            {
                nomeCompleto: 'Maria Oliveira',
                registroFuncional: 'RF125',
                cpf: '123.222.789-02',
                nomeSocial: 'Maria',
                sexo: 'Feminino',
                racaCor: 'Negra',
                grupoSanguineo: 'O-',
                dataNascimento: new Date('1990-03-10'),
                pais: 'Brasil',
                possuidorDeficiencia: true,
                tipoDeficiencia: 'Visual',
                uf: 'MG',
                cidade: 'Belo Horizonte',
                estadoCivil: 'Divorciada',
                escolaridade: 'Superior Completo',
                nacionalidade: 'Brasileira',
                numIdentidadeProfissional: '3456789',
                conselhoIdentidadeProfissional: 'CRN-MG',
                profissaoIdentidadeProfissional: 'Nutricionista',
                dataExpedicaoIdentidadeProfissional: new Date('2010-03-15'),
                especificacaoFormacao: 'Nutrição',
                anoChegadaBrasil: 2010,
                anoPrimeiroEmprego: 2020,
                existenciaCadastroCertidoes: 'Sim',
                endereco: 'Rua Exemplo, 789',
                cargoFuncao: 'Nutricionista',
                referenciaCargoFuncao: 'C3',
                provimentoCargoFuncao: 'Efetivo',
                dataInicioCargoFuncao: new Date('2015-03-01'),
                dataExoneracaoCargoFuncao: new Date('2020-03-01'),
                codigoUnidadeSIMPROC: 'S125',
                codigoUnidadeSEI: 'E125',
                cargoComissao: 'Comissionado',
                referenciaCargoComissao: 'C3',
                dataInicioCargoComissao: new Date('2016-03-01'),
                dataTerminoCargoComissao: new Date('2020-03-01'),
                unidadeLotacaoCargoComissao: 'Unidade 3',
                departamentoCoordenadoriaCargoComissao: 'Departamento 3',
                provimentoCargas: 'Posse',
                cargosLivresOcupados: '0',
                impedimentosLegais: 'Nenhum',
                dataInicioImpedimentosLegais: new Date('2010-03-01'),
                dataTerminoImpedimentosLegais: new Date('2020-03-01')
            },
            {
                nomeCompleto: 'Pedro Costa',
                registroFuncional: 'RF126',
                cpf: '123.333.789-03',
                nomeSocial: 'Pedro',
                sexo: 'Masculino',
                racaCor: 'Pardo',
                grupoSanguineo: 'B+',
                dataNascimento: new Date('1992-04-20'),
                pais: 'Brasil',
                possuidorDeficiencia: false,
                tipoDeficiencia: 'Nenhuma',
                uf: 'BA',
                cidade: 'Salvador',
                estadoCivil: 'Casado',
                escolaridade: 'Técnico',
                nacionalidade: 'Brasileiro',
                numIdentidadeProfissional: '4567890',
                conselhoIdentidadeProfissional: 'CREA-BA',
                profissaoIdentidadeProfissional: 'Técnico',
                dataExpedicaoIdentidadeProfissional: new Date('2015-04-10'),
                especificacaoFormacao: 'Técnico',
                anoChegadaBrasil: 2015,
                anoPrimeiroEmprego: 2025,
                existenciaCadastroCertidoes: 'Não',
                endereco: 'Rua Central, 101',
                cargoFuncao: 'Técnico',
                referenciaCargoFuncao: 'D4',
                provimentoCargoFuncao: 'Temporário',
                dataInicioCargoFuncao: new Date('2020-04-01'),
                dataExoneracaoCargoFuncao: new Date('2025-04-01'),
                codigoUnidadeSIMPROC: 'S126',
                codigoUnidadeSEI: 'E126',
                cargoComissao: 'Comissionado',
                referenciaCargoComissao: 'D4',
                dataInicioCargoComissao: new Date('2021-04-01'),
                dataTerminoCargoComissao: new Date('2025-04-01'),
                unidadeLotacaoCargoComissao: 'Unidade 4',
                departamentoCoordenadoriaCargoComissao: 'Departamento 4',
                provimentoCargas: 'Posse',
                cargosLivresOcupados: '1',
                impedimentosLegais: 'Nenhum',
                dataInicioImpedimentosLegais: new Date('2015-04-01'),
                dataTerminoImpedimentosLegais: new Date('2025-04-01')
            },
            {
                nomeCompleto: 'Ana Souza',
                registroFuncional: 'RF127',
                cpf: '123.444.789-04',
                nomeSocial: 'Ana',
                sexo: 'Feminino',
                racaCor: 'Branca',
                grupoSanguineo: 'A-',
                dataNascimento: new Date('1978-12-05'),
                pais: 'Brasil',
                possuidorDeficiencia: false,
                tipoDeficiencia: 'Nenhuma',
                uf: 'RS',
                cidade: 'Porto Alegre',
                estadoCivil: 'Solteira',
                escolaridade: 'Superior Completo',
                nacionalidade: 'Brasileira',
                numIdentidadeProfissional: '5678901',
                conselhoIdentidadeProfissional: 'CRN-RS',
                profissaoIdentidadeProfissional: 'Psicóloga',
                dataExpedicaoIdentidadeProfissional: new Date('2010-01-01'),
                especificacaoFormacao: 'Psicologia',
                anoChegadaBrasil: 2010,
                anoPrimeiroEmprego: 2020,
                existenciaCadastroCertidoes: 'Sim',
                endereco: 'Rua Principal, 200',
                cargoFuncao: 'Psicóloga',
                referenciaCargoFuncao: 'E5',
                provimentoCargoFuncao: 'Efetivo',
                dataInicioCargoFuncao: new Date('2015-01-01'),
                dataExoneracaoCargoFuncao: new Date('2020-01-01'),
                codigoUnidadeSIMPROC: 'S127',
                codigoUnidadeSEI: 'E127',
                cargoComissao: 'Comissionado',
                referenciaCargoComissao: 'E5',
                dataInicioCargoComissao: new Date('2016-01-01'),
                dataTerminoCargoComissao: new Date('2020-01-01'),
                unidadeLotacaoCargoComissao: 'Unidade 5',
                departamentoCoordenadoriaCargoComissao: 'Departamento 5',
                provimentoCargas: 'Posse',
                cargosLivresOcupados: '2',
                impedimentosLegais: 'Nenhum',
                dataInicioImpedimentosLegais: new Date('2010-01-01'),
                dataTerminoImpedimentosLegais: new Date('2020-01-01')
            },
            {
                nomeCompleto: 'Carlos Almeida',
                registroFuncional: 'RF128',
                cpf: '123.555.789-05',
                nomeSocial: 'Carlos',
                sexo: 'Masculino',
                racaCor: 'Pardo',
                grupoSanguineo: 'O+',
                dataNascimento: new Date('1982-11-20'),
                pais: 'Brasil',
                possuidorDeficiencia: true,
                tipoDeficiencia: 'Auditivo',
                uf: 'SP',
                cidade: 'São Paulo',
                estadoCivil: 'Casado',
                escolaridade: 'Superior Completo',
                nacionalidade: 'Brasileiro',
                numIdentidadeProfissional: '6789012',
                conselhoIdentidadeProfissional: 'CREA-SP',
                profissaoIdentidadeProfissional: 'Engenheiro',
                dataExpedicaoIdentidadeProfissional: new Date('2005-01-01'),
                especificacaoFormacao: 'Engenharia',
                anoChegadaBrasil: 2005,
                anoPrimeiroEmprego: 2015,
                existenciaCadastroCertidoes: 'Sim',
                endereco: 'Av. Central, 500',
                cargoFuncao: 'Engenheiro',
                referenciaCargoFuncao: 'F6',
                provimentoCargoFuncao: 'Efetivo',
                dataInicioCargoFuncao: new Date('2010-01-01'),
                dataExoneracaoCargoFuncao: new Date('2015-01-01'),
                codigoUnidadeSIMPROC: 'S128',
                codigoUnidadeSEI: 'E128',
                cargoComissao: 'Comissionado',
                referenciaCargoComissao: 'F6',
                dataInicioCargoComissao: new Date('2011-01-01'),
                dataTerminoCargoComissao: new Date('2015-01-01'),
                unidadeLotacaoCargoComissao: 'Unidade 6',
                departamentoCoordenadoriaCargoComissao: 'Departamento 6',
                provimentoCargas: 'Posse',
                cargosLivresOcupados: '1',
                impedimentosLegais: 'Nenhum',
                dataInicioImpedimentosLegais: new Date('2005-01-01'),
                dataTerminoImpedimentosLegais: new Date('2015-01-01')
            },
            {
                nomeCompleto: 'Juliana Mendes',
                registroFuncional: 'RF129',
                cpf: '123.666.789-06',
                nomeSocial: 'Juliana',
                sexo: 'Feminino',
                racaCor: 'Negra',
                grupoSanguineo: 'AB-',
                dataNascimento: new Date('1995-02-14'),
                pais: 'Brasil',
                possuidorDeficiencia: false,
                tipoDeficiencia: 'Nenhuma',
                uf: 'MG',
                cidade: 'Belo Horizonte',
                estadoCivil: 'Solteira',
                escolaridade: 'Superior Completo',
                nacionalidade: 'Brasileira',
                numIdentidadeProfissional: '7890123',
                conselhoIdentidadeProfissional: 'CRN-MG',
                profissaoIdentidadeProfissional: 'Assistente Social',
                dataExpedicaoIdentidadeProfissional: new Date('2015-02-15'),
                especificacaoFormacao: 'Serviço Social',
                anoChegadaBrasil: 2015,
                anoPrimeiroEmprego: 2025,
                existenciaCadastroCertidoes: 'Não',
                endereco: 'Rua Secundária, 600',
                cargoFuncao: 'Assistente Social',
                referenciaCargoFuncao: 'G7',
                provimentoCargoFuncao: 'Temporário',
                dataInicioCargoFuncao: new Date('2020-02-01'),
                dataExoneracaoCargoFuncao: new Date('2025-02-01'),
                codigoUnidadeSIMPROC: 'S129',
                codigoUnidadeSEI: 'E129',
                cargoComissao: 'Comissionado',
                referenciaCargoComissao: 'G7',
                dataInicioCargoComissao: new Date('2021-02-01'),
                dataTerminoCargoComissao: new Date('2025-02-01'),
                unidadeLotacaoCargoComissao: 'Unidade 7',
                departamentoCoordenadoriaCargoComissao: 'Departamento 7',
                provimentoCargas: 'Posse',
                cargosLivresOcupados: '0',
                impedimentosLegais: 'Nenhum',
                dataInicioImpedimentosLegais: new Date('2015-02-01'),
                dataTerminoImpedimentosLegais: new Date('2025-02-01')
            },
        ];
          
        return rows;
    }

    static get_columns_substitute():Column[] {
        const column: Column[] = [
            { header: 'Nome Social', accessor: 'nomeSocial', type: 'text' },
            { header: 'Registro Funcional', accessor: 'registroFuncional', type: 'text' },
            { header: 'Nome', accessor: 'nomeCompleto', type: 'text' },
            { header: 'Registro Funcional 2', accessor: 'registroFuncional', type: 'text' }, // TO check
            { header: 'Substituto (sem dados)', accessor: 'uf', type: 'text' },
            { header: 'Cargo', accessor: 'cargoComissao', type: 'text' }, // TO check
            { header: 'Referência', accessor: 'referenciaCargoComissao', type: 'text' }, // TO check
            { header: 'Mês de Referência', accessor: 'dataExoneracaoCargoFuncao', type: 'date' }, // TO check
            { header: 'Início', accessor: 'dataInicioCargoComissao', type: 'date' }, // TO check
            { header: 'Fim', accessor: 'dataTerminoCargoComissao', type: 'date' }, // TO check
            { header: 'Motivo (sem dados)', accessor: 'uf', type: 'text' },
            { header: 'Documento (sem dados)', accessor: 'uf', type: 'text' },
            { header: 'Conferência (sem dados)', accessor: 'uf', type: 'text' },
            { header: 'Observação (sem dados)', accessor: 'uf', type: 'text' }
        ] as Column[]

        return column
    }

    static get_columns_license():Column[] {
        const column: Column[] = [
            { header: 'RF', accessor: 'registroFuncional', type: 'text' },
            { header: 'Nome', accessor: 'nomeCompleto', type: 'text' },
            { header: 'Impedimentos Legais', accessor: 'impedimentosLegais', type: 'text' },
            { header: 'Inicio', accessor: 'dataInicioImpedimentosLegais', type: 'date' },
            { header: 'Término', accessor: 'dataTerminoImpedimentosLegais', type: 'date' }, 
            { header: 'Documento (fora da lista de campos)', accessor: 'uf', type: 'text' },
            { header: 'Conferência (fora da lista de campos)', accessor: 'uf', type: 'text' },
        ] as Column[]

        return column
    }

    static get_columns_promotion():Column[] {
        const column: Column[] = [
            { header: 'RF', accessor: 'registroFuncional', type: 'text' },
            { header: 'Nome', accessor: 'nomeCompleto', type: 'text' },
            { header: 'Evento', accessor: 'provimentoCargoFuncao', type: 'text' }, // TO check
            { header: 'Inicio', accessor: 'dataInicioCargoFuncao', type: 'date' },
            { header: 'Cargo', accessor: 'provimentoCargoFuncao', type: 'text' },
            { header: 'Documento (fora da lista de campos)', accessor: 'uf', type: 'text' },
            { header: 'Conferência (fora da lista de campos)', accessor: 'uf', type: 'text' },
        ] as Column[]

        return column
    }

    static get_columns_promot():Column[] {
        const column: Column[] = [
            { header: 'RF', accessor: 'registroFuncional', type: 'text' },
            { header: 'Nome', accessor: 'nomeCompleto', type: 'text' },
            { header: 'Cargo', accessor: 'cargoFuncao', type: 'text' },
            { header: 'Mês referência', accessor: 'referenciaCargoFuncao', type: 'text' }, // TO check
            { header: 'Início', accessor: 'dataInicioCargoFuncao', type: 'date' },
            { header: 'Exoneração', accessor: 'dataExoneracaoCargoFuncao', type: 'date' },
            { header: 'Publicação (fora da lista de campos)', accessor: 'uf', type: 'text' },
            { header: 'Observação (fora da lista de campos)', accessor: 'uf', type: 'text' },
            { header: 'Conferência (fora da lista de campos)', accessor: 'uf', type: 'text' },
        ] as Column[]

        return column
    }

    static get_sheet():Column[] {
        const column: Column[] = [
            { header: 'RF', accessor: 'registroFuncional', type: 'text' },
            { header: 'Nome', accessor: 'nomeCompleto', type: 'text' },
            { header: 'Vínculo', accessor: 'cargoFuncao', type: 'text' },
            { header: 'EH', accessor: 'uf', type: 'text' },
            { header: 'Unidade', accessor: 'uf', type: 'text' },
            { header: 'Mês referência', accessor: 'referenciaCargoFuncao', type: 'text' }, // TO check
        ] as Column[]

        return column
    }
}
